<a href="https://colab.research.google.com/github/Vaibhavipat1999/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np

<module 'numpy' from '/usr/local/lib/python3.10/dist-packages/numpy/__init__.py'>

In [ ]:
#1.Create a null vector of size 10 but the fifth value which is 1.

a=np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#2.Create a vector with values ranging from 10 to 49.

a=np.arange(10,50)
print (a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#3.Create a 3x3 matrix with values ranging from 0 to 8 

v =  np.arange(0, 9).reshape(3,3)
print(v)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#4.Find indices of non-zero elements from [1,2,0,0,4,0]
arr=np.array([1,2,0,0,4,0])
print("Non-zero elements of the array arr:",arr[np.nonzero(arr)])

Non-zero elements of the array arr: [1 2 4]


In [ ]:
#5. Create a 10x10 array with random values and find the minimum and maximum values.
a = np.random.random((10,10))
amin, amax = a.min(), a.max()
print(amin, amax)

0.01175761991130142 0.9940743478064681


In [ ]:
#6. Create a random vector of size 30 and find the mean value.

a = np.random.random(30)
b = a.mean()
print(b)


0.47777652960268296
